using Context.DataBaseContext;
using Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace Context.DataSeeder
{
    public static class PermissionSeedData
    {
        public static void Initialize(IServiceProvider serviceProvider)
        {
            using var context =
                new UserManagementContext(
                    serviceProvider.GetRequiredService<DbContextOptions<UserManagementContext>>());
            var permissionsToAdd = new List<Permission>
            {
                new Permission { Id = 1, Title = "باشگاه مشتریان", ParentId = null,ForClient = null },
                new Permission { Id = 2, Title = "تسهیلات بانکی", ParentId = 1,ForClient = null },
                new Permission { Id = 3, Title = "افزودن تسهیلات آنی", ParentId = 2,ForClient = false },
                new Permission { Id = 4, Title = "ویرایش تسهیلات آنی", ParentId = 2,ForClient = false },
                new Permission { Id = 5, Title = "حذف تسهیلات آنی", ParentId = 2,ForClient = false },
                new Permission { Id = 6, Title = "دریافت تاریخچه تسهیلات آنی", ParentId = 2,ForClient = false },
                new Permission { Id = 7, Title = "ایجاد شعبه", ParentId = 2,ForClient = false },
                new Permission { Id = 8, Title = "حذف شعبه", ParentId = 2,ForClient = false },
                new Permission { Id = 9, Title = "به روز رسانی شعبه", ParentId = 2,ForClient = false },
                new Permission { Id = 10, Title = "اضافه کردن خدمات بانکی جدید", ParentId = 2,ForClient = false },
                new Permission { Id = 11, Title = "ویرایش خدمات بانکی", ParentId = 2,ForClient = false },
                new Permission { Id = 12, Title = "حذف خدمات بانکی", ParentId = 2,ForClient = false },
                new Permission { Id = 13, Title = "تاریخچه مدیریت خدمات بانکی صفحه بندی شده", ParentId = 2,ForClient = false },
                new Permission { Id = 14, Title = "دریافت کلیه خدمات بانکی", ParentId = 2,ForClient = true },
                new Permission { Id = 15, Title = "تاریخچه کاربر خدمات بانکی صفحه بندی شده", ParentId = 2,ForClient= true },
                new Permission { Id = 16, Title = "Active SMSجزئیات سرویس ", ParentId = 2,ForClient = true },
                new Permission { Id = 17, Title = "برای کاربرSMS خرید و فعال کردن سرویس ", ParentId = 2,ForClient= true },
                new Permission { Id = 18, Title = "دریافت تمام تسهیلات آنی", ParentId = 2,ForClient = true },
                new Permission { Id = 19, Title = "دریافت تسهیلات آنی", ParentId = 2,ForClient = true },
                new Permission { Id = 20, Title = "خرید تسهیلات آنی", ParentId = 2,ForClient = true },
                new Permission { Id = 21, Title = "دریافت همه شهرها", ParentId = 2,ForClient = true },
                new Permission { Id = 22, Title = "دریافت همه شعبه ها", ParentId = 2,ForClient = true },
                new Permission { Id = 23, Title = "دریافت تاریخچه خرید کاربر", ParentId = 2,ForClient = true },
                new Permission { Id = 24, Title = "دریافت تمام تسهیلات آنی  بدون صفحه بندی", ParentId = 2,ForClient = true },
                new Permission { Id = 25, Title = "محاسبه تسهیلات بانکی", ParentId = 2,ForClient = true },
                new Permission { Id = 26, Title = "محاسبه اعداد تسهیلات", ParentId = 2,ForClient = true },
                new Permission { Id = 27, Title = "بازگشت وجه", ParentId = 1,ForClient = null },
                new Permission { Id = 28, Title = "اضافه کردن بازگشت وجه", ParentId = 27,ForClient = false },
                new Permission { Id = 29, Title = "به روز رسانی بازگشت وجه", ParentId = 27,ForClient = false },
                new Permission { Id = 30, Title = "دریافت بازگشت وجه", ParentId = 27,ForClient = false },
                new Permission { Id = 31, Title = "دریافت همه بازگشت وجه ها", ParentId = 27,ForClient = false },
                new Permission { Id = 32, Title = "حذف بازگشت وجه ", ParentId = 27,ForClient = false },
                new Permission { Id = 33, Title = "گزارش بازگشت وجه با صفحه بندی", ParentId = 27,ForClient = false },
                new Permission { Id = 34, Title = "گزارش بازگشت وجه بدون صفحه بندی", ParentId = 27,ForClient = false },
                new Permission { Id = 35, Title = "دریافت بازگشت وجه مشتری", ParentId = 27,ForClient = true },
                new Permission { Id = 36, Title = "دریافت همه بازگشت وجه", ParentId = 27,ForClient = true },
                new Permission { Id = 37, Title = "BI بازگشت وجه های ", ParentId = 27,ForClient = false },
                new Permission { Id = 38, Title = "انجام دادن دریافت بازگشت وجه مشتری", ParentId = 27,ForClient = true },
                new Permission { Id = 39, Title = "دریافت بازگشت وجه توسط شناسه تراکنش ", ParentId = 27,ForClient = true },
                new Permission { Id = 40, Title = "دریافت پذیرنده بدون بازگشت وجه", ParentId = 27,ForClient = true },
                new Permission { Id = 41, Title = "دریافت پذیرنده", ParentId = 27,ForClient = true },
                new Permission { Id = 42, Title = "کد تخفیف", ParentId = 1,ForClient = null },
                new Permission { Id = 43, Title = "اضافه کردن کد تخفیف", ParentId = 42,ForClient = false },
                new Permission { Id = 44, Title = "ویرایش کد تخفیف", ParentId = 42,ForClient = false },
                new Permission { Id = 45, Title = "حذف کد تخفیف", ParentId = 42,ForClient = false },
                new Permission { Id = 46, Title = "اضافه کردن دسته‌بندی", ParentId = 42,ForClient = false },
                new Permission { Id = 47, Title = "ویرایش دسته‌بندی", ParentId = 42,ForClient = false },
                new Permission { Id = 48, Title = "حذف دسته‌بندی", ParentId = 42,ForClient = false },
                new Permission { Id = 49, Title = "شارژ کدتخفیف - افزودن کد", ParentId = 42,ForClient = false },
                new Permission { Id = 50, Title = "شارژ کد تخفیف - افزودن کد با فایل", ParentId = 42,ForClient = false },
                new Permission { Id = 51, Title = "دریافت کد تخفیف ها - ادمین", ParentId = 42,ForClient = false },
                new Permission { Id = 52, Title = "دریافت کد تخفیف کاربران", ParentId = 42,ForClient = false },
                new Permission { Id = 53, Title = "دریافت کد تخفیف ها - کاربر", ParentId = 42,ForClient = true },
                new Permission { Id = 54, Title = "خرید", ParentId = 42,ForClient = true },
                new Permission { Id = 55, Title = "قوانین کد تخفیف", ParentId = 42,ForClient = true },
                new Permission { Id = 56, Title = "تاریخچه", ParentId = 42,ForClient = true },
                new Permission { Id = 57, Title = "دریافت کد تخفیف  - با شناسه", ParentId = 42,ForClient = true },
                new Permission { Id = 58, Title = "دریافت کد تخفیف ها بر اساس دسته‌بندی فیلتر شده", ParentId = 42,ForClient = true },
                new Permission { Id = 59, Title = "Flat دریافت همه کد تخفیف ها", ParentId = 42,ForClient = true },
                new Permission { Id = 60, Title = "استفاده از کد تخفیف", ParentId = 42,ForClient = true },
                new Permission { Id = 61, Title = "استفاده از کد تخفیف - با شناسه", ParentId = 42,ForClient = true },
                new Permission { Id = 62, Title = "دریافت همه دسته‌بندی ها", ParentId = 42,ForClient = true },
                new Permission { Id = 63, Title = "دریافت همه کلیدهای دسته‌بندی", ParentId = 42,ForClient = true },
                new Permission { Id = 64, Title = "دریافت مقادیر کلید دسته‌بندی", ParentId = 42,ForClient = true },
                new Permission { Id = 65, Title = "اهرم شانس", ParentId = 1,ForClient = null },
                new Permission { Id = 66, Title = "اضافه کردن اهرم شانس", ParentId = 65,ForClient = false },
                new Permission { Id = 67, Title = "به روز رسانی اهرم شانس", ParentId = 65,ForClient = false },
                new Permission { Id = 68, Title = "دریافت اهرم شانس - ادمین", ParentId = 65,ForClient = false },
                new Permission { Id = 69, Title = "دریافت همه اهرم شانس ها - ادمین", ParentId = 65,ForClient = false },
                new Permission { Id = 70, Title = "حذف اهرم شانس", ParentId = 65,ForClient = false },
                new Permission { Id = 71, Title = "اضافه کردن آواتار", ParentId = 65,ForClient = false },
                new Permission { Id = 72, Title = "حذف آواتار", ParentId = 65,ForClient = false },
                new Permission { Id = 73, Title = "دریافت گزارش های شرکت کنندگان", ParentId = 65,ForClient = false },
                new Permission { Id = 74, Title = "دریافت اطلاعات بازی اهرم شانس", ParentId = 65,ForClient = false },
                new Permission { Id = 75, Title = "دریافت اطلاعات شرکت کنندگان", ParentId = 65,ForClient = false },
                new Permission { Id = 76, Title = "بازی", ParentId = 65,ForClient = true },
                new Permission { Id = 77, Title = "دریافت اطلاعات بازی شرکت کنندگان", ParentId = 65,ForClient = true },
                new Permission { Id = 78, Title = "دریافت اهرم شانس  - با شناسه", ParentId = 65,ForClient = true },
                new Permission { Id = 79, Title = "دریافت همه اهرم شانس ها", ParentId = 65,ForClient = true },
                new Permission { Id = 80, Title = "صفحه اصلی", ParentId = 1,ForClient = null },
                new Permission { Id = 81, Title = "اضافه یا بروزرسانی بنر", ParentId = 80,ForClient = false },
                new Permission { Id = 82, Title = "حذف بنر", ParentId = 80,ForClient = false },
                new Permission { Id = 83, Title = "دریافت بنر", ParentId = 80,ForClient = true },
                new Permission { Id = 84, Title = "دریافت بنر ها", ParentId = 80,ForClient = true },
                new Permission { Id = 85, Title = "افزودن سوالات متداول جدید", ParentId = 80,ForClient = false },
                new Permission { Id = 86, Title = "ویرایش سوالات متداول", ParentId = 80,ForClient = false },
                new Permission { Id = 87, Title = "حذف سوالات متداول", ParentId = 80,ForClient = false },
                new Permission { Id = 88, Title = "دریافت سوالات متداول", ParentId = 80,ForClient = true },
                new Permission { Id = 89, Title = "دریافت همه موارد سوالات متداول", ParentId = 80,ForClient = true },
                new Permission { Id = 90, Title = "اضافه کردن آیتم", ParentId = 80,ForClient = false },
                new Permission { Id = 91, Title = "حذف آیتم", ParentId = 80,ForClient = false },
                new Permission { Id = 92, Title = "دریافت آیتم ها", ParentId = 80,ForClient = true },
                new Permission { Id = 93, Title = "ویرایش آیتم", ParentId = 80,ForClient = false },
                new Permission { Id = 94, Title = "تعداد کاربران آنلاین", ParentId = 80,ForClient = true },
                new Permission { Id = 95, Title = "دریافت کاربران آنلاین", ParentId = 80,ForClient = false },
                new Permission { Id = 96, Title = "دریافت اطلاعات افزونه قلک", ParentId = 80,ForClient = true },
                new Permission { Id = 97, Title = "قرعه‌کشی", ParentId = 1,ForClient = null },
                new Permission { Id = 98, Title = "اضافه کردن قرعه‌کشی", ParentId = 97,ForClient = false },
                new Permission { Id = 99, Title = "ویرایش قرعه‌کشی", ParentId = 97,ForClient = false },
                new Permission { Id = 100, Title = "حذف قرعه‌کشی", ParentId = 97,ForClient = false },
                new Permission { Id = 101, Title = "دریافت تاریخچه قرعه‌کشی", ParentId = 97,ForClient = false },
                new Permission { Id = 102, Title = "شرکت در قرعه‌کشی", ParentId = 97,ForClient = true },
                new Permission { Id = 103, Title = "دریافت قرعه‌کشی ها", ParentId = 97,ForClient = true },
                new Permission { Id = 104, Title = "دریافت قوانین قرعه‌کشی ها", ParentId = 97,ForClient = true },
                new Permission { Id = 105, Title = "دریافت تاریخچه قرعه‌کشی کاربر", ParentId = 97,ForClient = true },
                new Permission { Id = 106, Title = "دریافت اطلاعات قرعه‌کشی", ParentId = 97,ForClient = true },
                new Permission { Id = 107, Title = "دریافت تاریخچه کاربران قرعه‌کشی", ParentId = 97,ForClient = false },
                new Permission { Id = 108, Title = "چرخ گردون", ParentId = 1,ForClient = null },
                new Permission { Id = 109, Title = "اضافه کردن چرخ گردون", ParentId = 108,ForClient = false },
                new Permission { Id = 110, Title = "حذف چرخ گردون", ParentId = 108,ForClient = false },
                new Permission { Id = 111, Title = "خرید بلیط چرخ گردون", ParentId = 108,ForClient = true },
                new Permission { Id = 112, Title = "دریافت گروه چرخ گردون ها", ParentId = 108,ForClient = true },
                new Permission { Id = 113, Title = "دریافت موارد چرخ گردون", ParentId = 108,ForClient = true },
                new Permission { Id = 114, Title = "چرخش چرخ گردون", ParentId = 108,ForClient = true },
                new Permission { Id = 115, Title = "دریافت تاریخچه کاربر", ParentId = 108,ForClient = true },
                new Permission { Id = 116, Title = "پذیرنده", ParentId = 1,ForClient = null },
                new Permission { Id = 117, Title = "دریافت پذیرنده با شناسه", ParentId = 116,ForClient = true },
                new Permission { Id = 118, Title = "دریافت پذیرنده", ParentId = 116,ForClient = true },
                new Permission { Id = 119, Title = "دریافت پذیرنده بدون ترمینال", ParentId = 116,ForClient = true },
                new Permission { Id = 120, Title = "اضافه کردن پذیرنده", ParentId = 116,ForClient = false },
                new Permission { Id = 121, Title = "ویرایش پذیرنده", ParentId = 116,ForClient = false },
                new Permission { Id = 122, Title = "پذیرنده", ParentId = 116,ForClient = true },
                new Permission { Id = 123, Title = "حذف پذیرنده", ParentId = 116,ForClient = false },
                new Permission { Id = 124, Title = "اضافه کردن ترمینال", ParentId = 116,ForClient = false },
                new Permission { Id = 125, Title = "ویرایش ترمینال", ParentId = 116,ForClient = false },
                new Permission { Id = 126, Title = "حذف ترمینال", ParentId = 116,ForClient = false },
                new Permission { Id = 127, Title = "دریافت ترمینال ها با شناسه پذیرنده", ParentId = 116,ForClient = true },
                new Permission { Id = 128, Title = "دریافت پذیرنده با شناسه", ParentId = 116,ForClient = true },
                new Permission { Id = 129, Title = "دریافت پذیرنده - با شناسه", ParentId = 116,ForClient = true },
                new Permission { Id = 130, Title = "مدیریت امتیاز کاربر", ParentId = 1,ForClient = null },
                new Permission { Id = 131, Title = "دریافت امتیاز کاربر", ParentId = 130,ForClient = true },
                new Permission { Id = 132, Title = "دریافت امتیاز کاربربا شناسه کاربر", ParentId = 130,ForClient = true },
                new Permission { Id = 133, Title = "تراکنش های کاربر صفحه بندی شده ", ParentId = 130,ForClient = true },
                new Permission { Id = 134, Title = "مشتریClv اطلاعات", ParentId = 130,ForClient = true },
                new Permission { Id = 135, Title = "دریافت امتیاز های ماهانه کاربر", ParentId = 130,ForClient = true },
                new Permission { Id = 136, Title = "دریافت امتیازهای کسب شده در ماه جاری کاربر", ParentId = 130,ForClient = true },
                new Permission { Id = 137, Title = "دریافت امتیازهای تشویقی کاربر", ParentId = 130,ForClient = true },
                new Permission { Id = 138, Title = "مشخصات ", ParentId = 1,ForClient = null },
                new Permission { Id = 139, Title = "دریافت ویژگی های مشخصات", ParentId = 138,ForClient = false },
                new Permission { Id = 140, Title = "اضافه کردن ویژگی مشخصات", ParentId = 138,ForClient = false },
                new Permission { Id = 141, Title = " ویرایش ویژگی مشخصات", ParentId = 138,ForClient = false },
                new Permission { Id = 142, Title = "گردشگری", ParentId = 1,ForClient = null },
                new Permission { Id = 143, Title = "اضافه کردن فرودگاه جدید", ParentId = 142,ForClient = false },
                new Permission { Id = 144, Title = "ویرایش فرودگاه", ParentId = 142,ForClient = false },
                new Permission { Id = 145, Title = "حذف فرودگاه", ParentId = 142,ForClient = false },
                new Permission { Id = 146, Title = "اضافه کردن قانون جدید", ParentId = 142,ForClient = false },
                new Permission { Id = 147, Title = "ویرایش قانون", ParentId = 142,ForClient = false },
                new Permission { Id = 148, Title = "حذف قانون", ParentId = 142,ForClient = false },
                new Permission { Id = 149, Title = "ویرایش سرویس گردشگری", ParentId = 142,ForClient = false },
                new Permission { Id = 150, Title = "Cipلیست درخواست های", ParentId = 142,ForClient = false },
                new Permission { Id = 151, Title = "دریافت تاریخچه مدیریت انتقال", ParentId = 142,ForClient = false },
                new Permission { Id = 152, Title = "دریافت تمامی فرودگاه ها - درخواست صفحه بندی", ParentId = 142,ForClient = true },
                new Permission { Id = 153, Title = "دریافت تمامی فرودگاه ها", ParentId = 142,ForClient = true },
                new Permission { Id = 154, Title = "دریافت یک فرودگاه  - با شناسه", ParentId = 142,ForClient = true },
                new Permission { Id = 155, Title = "خرید ترانسفر فرودگاهی", ParentId = 142,ForClient = true },
                new Permission { Id = 156, Title = "CIP خرید فرودگاه ", ParentId = 142,ForClient = true },
                new Permission { Id = 157, Title = "دریافت تمامی سرویس گردشگری", ParentId = 142,ForClient = true },
                new Permission { Id = 158, Title = "دریافت یک سرویس گردشگری - با شناسه", ParentId = 142,ForClient = true },
                new Permission { Id = 159, Title = "کاربرCIP دریافت تاریخچه", ParentId = 142,ForClient = true },
                new Permission { Id = 160, Title = "دریافت تاریخچه ترنسفر کاربر", ParentId = 142,ForClient = true },
                new Permission { Id = 161, Title = "دریافت پروفایل کاربر", ParentId = 138,ForClient = true },
                new Permission { Id = 162, Title = "اضافه کردن پروفایل کاربر", ParentId = 138,ForClient = true },
                new Permission { Id = 163, Title = "ویرایش پروفایل کاربر", ParentId = 138,ForClient = true },
                new Permission { Id = 164, Title = "حذف پروفایل کاربر", ParentId = 138,ForClient = true },
                new Permission { Id = 165, Title = "تغییر وضعیت یک تخفیف", ParentId = 42,ForClient = false },
                new Permission { Id = 166, Title = "تغییر وضعیت قرعه‌کشی", ParentId = 97,ForClient = false },
                new Permission { Id = 167, Title = "تغییر وضعیت یک کاور صفحه اصلی", ParentId = 80,ForClient = false },
                new Permission { Id = 168, Title = "تغییر وضعیت یک آیتم صفحه اصلی", ParentId = 80,ForClient = false },
                new Permission { Id = 169, Title = "دریافت لیست کاورها برای کاربر", ParentId = 80,ForClient = true },
                new Permission { Id = 170, Title = "دریافت لیست آیتم‌ها برای کاربر", ParentId = 80,ForClient = true },
                new Permission { Id = 171, Title = "دریافت لیست قوانین یک کدتخفیف برای ادمین", ParentId = 42,ForClient = false },
                new Permission { Id = 172, Title = "گزارش مصرف کدهای یک تخفیف", ParentId = 42,ForClient = false },
                new Permission { Id = 173, Title = "دریافت گزارش اکسل کلی کدهای تخفیف", ParentId = 42,ForClient = false },
                new Permission { Id = 174, Title = "دریافت گزارش اکسل جزییات یک کد تخفیف", ParentId = 42,ForClient = false },
                new Permission { Id = 175, Title = "مدیریت کاربران", ParentId = null,ForClient = null },
                new Permission { Id = 176, Title = "احراز هویت", ParentId = 175,ForClient = null },
                new Permission { Id = 177, Title = "اضافه کردن دسترسی ها به نقش", ParentId = 176,ForClient = false },
                new Permission { Id = 178, Title = "دریافت دسترسی", ParentId = 176,ForClient = false },
                new Permission { Id = 179, Title = "به روز رسانی های دسترسی های نقش", ParentId = 176,ForClient = false },
                new Permission { Id = 180, Title = "اضافه کردن نقش با دسترسی", ParentId = 176,ForClient = false },
                new Permission { Id = 181, Title = "اضافه کردن نقش ها به کاربر", ParentId = 176,ForClient = false },
                new Permission { Id = 182, Title = "دریافت نقش ها با دسترسی ها", ParentId = 176,ForClient = false },
                new Permission { Id = 183, Title = "حذف نقش", ParentId = 176,ForClient = false },
                new Permission { Id = 184, Title = "به روزرسانی نقش ها", ParentId = 176,ForClient = false },
                new Permission { Id = 185, Title = "به روزرسانی نقش های کاربر", ParentId = 176,ForClient = false },
                new Permission { Id = 186, Title = "فعال و غیر فعال کردن نقش", ParentId = 176,ForClient = false },
                new Permission { Id = 187, Title = "جستجوی نقش ها", ParentId = 176,ForClient = false },
                new Permission { Id = 188, Title = "دریافت نقش", ParentId = 176,ForClient = false },
                new Permission { Id = 189, Title = "دریافت لیست کاربران", ParentId = 176,ForClient = false },
                new Permission { Id = 190, Title = "اضافه کردن کاربر", ParentId = 176,ForClient = false },
                new Permission { Id = 191, Title = "دربافت کاربر با نقش ها", ParentId = 176,ForClient = false },
                new Permission { Id = 192, Title = "به روزرسانی رمز عبور", ParentId = 176,ForClient = false },
                new Permission { Id = 193, Title = "به روزرسانی کاربران", ParentId = 176,ForClient = false },
                new Permission { Id = 194, Title = "تغییر وضعیت کاربر", ParentId = 176,ForClient = false },
                new Permission { Id = 195, Title = "دریافت کاربر با شناسه", ParentId = 176,ForClient = false },
                new Permission { Id = 196, Title = "اطلاعات کاربران", ParentId = 176,ForClient = false },
                new Permission { Id = 197, Title = "دریافت قرعه‌کشی‌ها سمت ادمین", ParentId = 97,ForClient = false },
                new Permission { Id = 198, Title = "دریافت گزارش کلی قرعه‌کشی", ParentId = 97,ForClient = false },
                new Permission { Id = 199, Title = "دریافت گزارش جزییات قرعه کشی", ParentId = 97,ForClient = false },
                new Permission { Id = 200, Title = "پروفایل", ParentId = null,ForClient = false },
                new Permission { Id = 201, Title = "دریافت تکی سکشن پروفایل (ادمین)", ParentId = 200,ForClient = false },
                new Permission { Id = 202, Title = "دریافت همه سکشن های پروفایل (ادمین)", ParentId = 200,ForClient = false },
                new Permission { Id = 203, Title = "دریافت تکی آیتم پروفایل (ادمین)", ParentId = 200,ForClient = false },
                new Permission { Id = 204, Title = "دریافت همه آیتم های پروفایل (ادمین)", ParentId = 200,ForClient = false },
                new Permission { Id = 205, Title = "دریافت تکی سکشن پروفایل (کاربر)", ParentId = 200,ForClient = true },
                new Permission { Id = 206, Title = "دریافت همه سکشن های پروفایل (کاربر)", ParentId = 200,ForClient = true },
                new Permission { Id = 207, Title = "دریافت تکی آیتم پروفایل (کاربر)", ParentId = 200,ForClient = true },
                new Permission { Id = 208, Title = "دریافت همه آیتم های پروفایل (کاربر)", ParentId = 200,ForClient = true },
                new Permission { Id = 209, Title = "دریافت اطلاعات پروفایل (کاربر)", ParentId = 200,ForClient = true },
                new Permission { Id = 210, Title = "ویرایش اطلاعات پروفایل (کاربر)", ParentId = 200,ForClient = true },
                new Permission { Id = 211, Title = "افزودن آیتم پروفایل (ادمین)", ParentId = 200,ForClient = false },
                new Permission { Id = 212, Title = "ویرایش آیتم پروفایل (ادمین)", ParentId = 200,ForClient = false },
                new Permission { Id = 213, Title = "حذف آیتم پروفایل (ادمین)", ParentId = 200,ForClient = false },
                new Permission { Id = 214, Title = "بازچینی ترتیب سکشن های پروفایل (ادمین)", ParentId = 200,ForClient = false },
                new Permission { Id = 215, Title = "بازچینی ترتیب آیتم های پروفایل (ادمین)", ParentId = 200,ForClient = false },
                new Permission { Id = 216, Title = "تغییر وضعیت فعال/غیرفعال سکشن پروفایل (ادمین)", ParentId = 200,ForClient = false },
                new Permission { Id = 217, Title = "تغییر وضعیت فعال/غیرفعال آیتم پروفایل (ادمین)", ParentId = 200,ForClient = false },

                new Permission { Id = 218, Title = "افزودن کاور بنر", ParentId = 80,ForClient = false },
                new Permission { Id = 219, Title = "افزودن باکس بنر", ParentId = 80,ForClient = false },
                new Permission { Id = 220, Title = "افزودن بنر", ParentId = 80,ForClient = false },
                new Permission { Id = 221, Title = "دریافت کاور بنر", ParentId = 80,ForClient = false },
                new Permission { Id = 222, Title = "دریافت باکس بنر", ParentId = 80,ForClient = false },
                new Permission { Id = 223, Title = "دریافت بنر ها با تایپ", ParentId = 80,ForClient = false },
                new Permission { Id = 224, Title = "دریافت بنر با ایدی", ParentId = 80,ForClient = false },
                new Permission { Id = 225, Title = "بروز رسانی باکس بنر", ParentId = 80,ForClient = false },
                new Permission { Id = 226, Title = "مرتب سازی باکس بنر", ParentId = 80,ForClient = false },
                new Permission { Id = 227, Title = "مرتب سازی بنر", ParentId = 80,ForClient = false },
                new Permission { Id = 228, Title = "بروز رسانی کاور بنر", ParentId = 80,ForClient = false },
                new Permission { Id = 229, Title = "بروز رسانی بنر", ParentId = 80,ForClient = false },
                new Permission { Id = 230, Title = "فعال و غیر فعال سازی بنر", ParentId = 80,ForClient = false },
                new Permission { Id = 231, Title = "فعال و غیر فعال سازی باکس بنر", ParentId = 80,ForClient = false },
                new Permission { Id = 232, Title = "فعال و غیر فعال سازی کاور بنر", ParentId = 80,ForClient = false },
                new Permission { Id = 233, Title = "فعال و غیر فعال سازی بنر های بالا", ParentId = 80,ForClient = false },
                new Permission { Id = 234, Title = "فعال و غیر فعال سازی بنر های پایین", ParentId = 80,ForClient = false },
                new Permission { Id = 235, Title = "فعال و غیر فعال سازی بنر های رول", ParentId = 80,ForClient = false },
                new Permission { Id = 236, Title = "دریافت بخش ها", ParentId = 80,ForClient = false },
                new Permission { Id = 237, Title = "حذف بنر ", ParentId = 80,ForClient = false },
                new Permission { Id = 238, Title = "تغییر وضعیت فعال/غیرفعال سکشن های پروفایل (ادمین)", ParentId = 200,ForClient = false },
                new Permission { Id = 239, Title = "تغییر وضعیت فعال/غیرفعال آیتم های پروفایل (ادمین)", ParentId = 200,ForClient = false },

                new Permission { Id = 240, Title = "تغییر وضعیت فعال/غیرفعال اهرم شانس", ParentId = 65,ForClient = false },
                new Permission { Id = 241, Title = " گزارش بنر ها", ParentId = 80,ForClient = false },
                new Permission { Id = 242, Title = "افزودن لاگ بنر ", ParentId = 80,ForClient = true },
                new Permission { Id = 243, Title = "دریافت گزارش ثبت نام کاربران", ParentId = 176,ForClient = false },

                new Permission { Id = 244, Title = "تغییر وضعیت فعال/غیرفعال پذیرنده", ParentId = 116,ForClient = false },
                new Permission { Id = 245, Title = "دریافت شعبات", ParentId = 116,ForClient = false },
                new Permission { Id = 246, Title = "دریافت یک شعبه با ایدی", ParentId = 116,ForClient = false },
                new Permission { Id = 247, Title = "افزودن شعبه", ParentId = 116,ForClient = false },
                new Permission { Id = 248, Title = "ویرایش شعبه", ParentId = 116,ForClient = false },
                new Permission { Id = 249, Title = "حذف شعبه", ParentId = 116,ForClient = false },
                new Permission { Id = 250, Title = "تغییر وضعیت فعال/غیرفعال شعبه", ParentId = 116,ForClient = false },
                new Permission { Id = 251, Title = "دریافت ترمینال‌ها", ParentId = 116,ForClient = false },
                new Permission { Id = 252, Title = "دریافت یک ترمینال با ایدی", ParentId = 116,ForClient = false },
                new Permission { Id = 253, Title = "تغییر وضعیت فعال/غیرفعال ترمینال", ParentId = 116,ForClient = false },
                new Permission { Id = 254, Title = "افزودن گروهی ترمینال", ParentId = 116,ForClient = false },
                new Permission { Id = 255, Title = "دریافت نوع قرارداد", ParentId = 116,ForClient = false },
                new Permission { Id = 256, Title = "چک کردن وجود داشتن پذیرنده با ایدی", ParentId = 116,ForClient = true },

                new Permission { Id = 257, Title = "حذف کدهای تخفیف با فایل", ParentId = 42,ForClient = false },

                new Permission { Id = 258, Title = "دریافت شعبات بدون صحفه‌بندی", ParentId = 116,ForClient = false },
                new Permission { Id = 259, Title = "دریافت پذیرنده‌ها بدون صحفه‌بندی", ParentId = 116,ForClient = false },

                new Permission { Id = 260, Title = "ویرایش قوانین قرعه کشی", ParentId = 97,ForClient = false },
                new Permission { Id = 261, Title = "دریافت اطلاعات قرعه کشی با شناسه", ParentId = 97,ForClient = false },
                new Permission { Id = 262, Title = "دریافت قوانین قرعه‌کشی با شناسه", ParentId = 97,ForClient = false },

                new Permission { Id = 263, Title = "اطلاعات پایه", ParentId = 1,ForClient = false },
                new Permission { Id = 264, Title = "دریافت کتگوری‌ها", ParentId = 263,ForClient = false },
                new Permission { Id = 265, Title = "اضافه نمودن کتگوری", ParentId = 263,ForClient = false },
                new Permission { Id = 266, Title = "ویرایش کتگوری", ParentId = 263,ForClient = false },
                new Permission { Id = 267, Title = "حذف کتگوری", ParentId = 263,ForClient = false },
                new Permission { Id = 268, Title = "تغییر وضعیت فعال/غیرفعال کتگوری", ParentId = 263,ForClient = false },
                new Permission { Id = 269, Title = "بازچینی ترتیب کتگوری‌ها", ParentId = 263,ForClient = false },


                new Permission { Id = 270, Title = "دریافت اطلاعات یک کدتخفیف - ادمین", ParentId = 42,ForClient = false },

                new Permission { Id = 271, Title = "دریافت کتگوری‌ها با لیستی از ایدی‌ها", ParentId = 263,ForClient = false },

                new Permission { Id = 272, Title = "دریافت کتگوری با ایدی پذیرنده", ParentId = 116,ForClient = false },

                new Permission { Id = 273, Title = "گزارش کدهای تخفیف به ازای هر کاربر", ParentId = 42,ForClient = false },

                new Permission { Id = 274, Title = "گزارش قرعه‌کشی به ازای هر کاربر", ParentId = 97,ForClient = false },
                new Permission { Id = 275, Title = "دریافت گزارش قرعه ‌کشی با صفحه‌بندی", ParentId = 97,ForClient = false },
                new Permission { Id = 276, Title = "دریافت اطلاعات یک سطح", ParentId = 263,ForClient = true },
                new Permission { Id = 277, Title = "دریافت اطلاعات همه سطوح", ParentId = 263,ForClient = true },

                new Permission { Id = 278, Title = "دریافت لاگ چرخ گردان", ParentId = 108,ForClient = false },
                new Permission { Id = 279, Title = "تغییر وضعیت فعال/غیرفعال چرخ گردان", ParentId = 108,ForClient = false },
                new Permission { Id = 280, Title = "ویرایش چرخ گردان", ParentId = 108,ForClient = false },
                new Permission { Id = 281, Title = "دریافت یک چرخ گردان", ParentId = 108,ForClient = false },

                new Permission { Id = 282, Title = "دریافت لاگ اهرم شانس", ParentId = 65,ForClient = false },

                new Permission { Id = 283, Title = "دریافت کتگوری‌ها‌ برای کاربران", ParentId = 263,ForClient = true },

                new Permission { Id = 284, Title = "دریافت لیست چرخ گردان‌ها", ParentId = 108,ForClient = false },

                new Permission { Id = 285, Title = "روند دریافت امتیاز برای کاربر", ParentId = 130,ForClient = true },
                new Permission { Id = 286, Title = "روند خرج کردن امتیاز برای کاربر", ParentId = 130,ForClient = true },
                new Permission { Id = 287, Title = "روند کلی امتیاز برای کاربر", ParentId = 130,ForClient = true },
                new Permission { Id = 288, Title = "اطلاعات نمودار امتیازات برای کاربر", ParentId = 130,ForClient = true },

                new Permission { Id = 289, Title = "گزارش جزییات یک چرخ گردان", ParentId = 108,ForClient = false },

                new Permission { Id = 290, Title = "گزارش جزییات یک اهرم شانس", ParentId = 65,ForClient = false },

                new Permission { Id = 291, Title = "غیرفعال کردن کدتخفیف با ایدی پذیرنده", ParentId = 42,ForClient = false },

                new Permission { Id = 292, Title = "دریافت گزارش جزییات قرعه ‌کشی با صفحه‌بندی", ParentId = 97,ForClient = false },

                new Permission { Id = 293, Title = "دریافت گزارش جزییات کدتخفیف با صفحه‌بندی", ParentId = 42,ForClient = false },

                new Permission { Id = 294, Title = "افزودن سوال با کتگوری", ParentId = 80,ForClient = false },
                new Permission { Id = 295, Title = "ویرایش سوال پرتکرار با کتگوری", ParentId = 80,ForClient = false },
                new Permission { Id = 296, Title = "حذف سوال پرتکرار", ParentId = 80,ForClient = false },
                new Permission { Id = 297, Title = "دریافت سوال پرتکرار با ایدی", ParentId = 80,ForClient = false },
                new Permission { Id = 298, Title = "بازچینی ترتیب سوالات پرتکرار", ParentId = 80,ForClient = false },
                new Permission { Id = 299, Title = "بازچینی ترتیب سوالات پرتکرار برای یک کتگوری", ParentId = 80,ForClient = false },
                new Permission { Id = 300, Title = "افزودن کتگوری", ParentId = 80,ForClient = false },
                new Permission { Id = 301, Title = "ویرایش کتگوری", ParentId = 80,ForClient = false },
                new Permission { Id = 302, Title = "حذف کتگوری", ParentId = 80,ForClient = false },
                new Permission { Id = 303, Title = "بازچینی ترتیب کتگوری", ParentId = 80,ForClient = false },
                new Permission { Id = 304, Title = "دریافت کاور بنر", ParentId = 80,ForClient = true },
                new Permission { Id = 305, Title = "دریافت باکس بنر", ParentId = 80,ForClient = true },
                new Permission { Id = 306, Title = "دریافت بنرها", ParentId = 80,ForClient = true },
                new Permission { Id = 307, Title = "دریافت سوالات پرتکرار با کتگوری", ParentId = 80,ForClient = true },
                new Permission { Id = 308, Title = "دریافت کتگوری‌ها", ParentId = 80,ForClient = true },
                new Permission { Id = 309, Title = "دریافت سکشن‌ها", ParentId = 80,ForClient = true },
                new Permission { Id = 310, Title = "دریافت اطلاعات صفحه درباره‌ی ما", ParentId = 80,ForClient = true },
                new Permission { Id = 311, Title = "دریافت اطلاعات صفحه قوانین و مقررات", ParentId = 80,ForClient = true },
                new Permission { Id = 312, Title = "دریافت اطلاعات صفحه ارتباط با ما", ParentId = 80,ForClient = true },
                new Permission { Id = 313, Title = "فعال و غیر فعال کردن بکس بنر", ParentId = 80,ForClient = false },
                new Permission { Id = 314, Title = "حذف بکس بنر", ParentId = 80,ForClient = false },

                new Permission { Id = 315, Title = "نظرسنجی", ParentId = 1,ForClient = null },
                new Permission { Id = 316, Title = "افزودن نظرسنجی", ParentId = 315,ForClient = false },
                new Permission { Id = 317, Title = "ویرایش نظرسنجی", ParentId = 315,ForClient = false },
                new Permission { Id = 318, Title = "تغییر وضعیت فعال/غیرفعال نظرسنجی", ParentId = 315,ForClient = false },
                new Permission { Id = 319, Title = "دریافت نظرسنجی با ایدی", ParentId = 315,ForClient = false },
                new Permission { Id = 320, Title = "دریافت نظرسنجی‌ها با صفحه‌بندی", ParentId = 315,ForClient = false },
                new Permission { Id = 321, Title = "افزودن سوال", ParentId = 315,ForClient = false },
                new Permission { Id = 322, Title = "ویرایش سوال", ParentId = 315,ForClient = false },
                new Permission { Id = 323, Title = "بازچینی ترتیب سوالات", ParentId = 315,ForClient = false },
                new Permission { Id = 324, Title = "دریافت سوالات با ایدی نظرسنجی", ParentId = 315,ForClient = false },
                new Permission { Id = 325, Title = "دریافت سوال با ایدی", ParentId = 315,ForClient = false },
                new Permission { Id = 326, Title = "حذف یک سوال", ParentId = 315,ForClient = false },
                new Permission { Id = 327, Title = "چک کردن وجود پاسخ برای یک نظرسنجی", ParentId = 315,ForClient = false },
                new Permission { Id = 328, Title = "دریافت گزارش کلی نظرسنجی‌ها", ParentId = 315,ForClient = false },
                new Permission { Id = 329, Title = "دریافت نظرسنجی‌ها بدون صفحه‌بندی", ParentId = 315,ForClient = false },
                new Permission { Id = 330, Title = "دریافت نظرسنجی‌ها برای کاربر", ParentId = 315,ForClient = true },
                new Permission { Id = 331, Title = "دریافت نظرسنجی با ایدی برای کاربر", ParentId = 315,ForClient = true },
                new Permission { Id = 332, Title = "دریافت نظرسنجی با سوالاتش", ParentId = 315,ForClient = true },
                new Permission { Id = 333, Title = "افزودن پاسخ برای نظرسنجی", ParentId = 315,ForClient = true },
                new Permission { Id = 334, Title = "چک کردن وجود پاسخ برای یک نظرسنجی برای کاربر", ParentId = 315,ForClient = true },
                new Permission { Id = 335, Title = "گزارش جزییات پاسخ کاربران به نظرسنجی", ParentId = 315,ForClient = false },

                new Permission { Id = 336, Title = "روند دریافت امتیاز با شماره مشتری", ParentId = 130,ForClient = true },
                new Permission { Id = 337, Title = "روند خرج کردن امتیاز با شماره مشتری", ParentId = 130,ForClient = true },
                new Permission { Id = 338, Title = "روند کلی امتیاز با شماره مشتری", ParentId = 130,ForClient = true },
                new Permission { Id = 339, Title = "اطلاعات نمودار امتیازات با شماره مشتری", ParentId = 130,ForClient = true },

                new Permission { Id = 340, Title = "دریافت کاربر با شماره مشتری", ParentId = 176,ForClient = false },
            };
            var table = context.Permissions.ToList();
            if (table.Count == 0)
            {
                context.Permissions.AddRange(permissionsToAdd);
                context.SaveChanges();
            }

            if (permissionsToAdd.Count <= table.Count) return;
            var maxIdInTable = context.Permissions.Max(p => p.Id);
            var newPermissions = permissionsToAdd.Where(p => p.Id > maxIdInTable).ToList();

            if (newPermissions.Count <= 0) return;
            context.Permissions.AddRange(newPermissions);
            context.SaveChanges();
        }
    }
} 